default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace # Remove unnecessary whitespace at the end of lines
      - id: end-of-file-fixer # Ensures a newline at the end of the file
      - id: check-docstring-first # Ensure that the documentation string immediately follows the function definition
      - id: check-yaml # Check YAML files for syntax errors
      - id: detect-private-key # Check if private key is uncommitted
      - id: check-toml # Check your TOML files for syntax errors
      - id: check-case-conflict # Detect case conflicts in file names
      - id: check-added-large-files # Warn if a file larger than a certain size is added

  # python linter and formatter
  - repo: local # use local ruff
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff-lint
        types_or: [python, jupyter]
        entry: ruff check . --fix
        language: python

      # Run the formatter.
      - id: ruff-format
        name: ruff-format
        entry: ruff format .
        language: python
        types_or: [python, jupyter]

  # yaml, json formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml, json]

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        args: ["--number"] # Automatically number headings in a file
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          # - mdformat-toc  # Automatically generate a table of contents
          # - mdformat-black  # Formatting code within a code block

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb
          # - --ignore-words-list=abc,def

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
